name: 'UiPath Test'
description: 'Runs test cases within a UiPath project'
inputs:
  projectFilePaths:
    description: 'Used for passing explicit paths to project files to perform analysis. Can be used as multi-line inputs'
    required: false
  orchestratorUrl: 
    description: 'Orchestrator instance URL'
    required: false
    default: "https://cloud.uipath.com/"
  orchestratorTenant:
    description: 'Tenant on the Orchestrator instance'
    required: true
  orchestratorFolder:
    description: 'Folder path in modern folder setup'
    required: true
  orchestratorApplicationId:
    description: 'Account for authenticating to Orchestrator'
    required: true
  orchestratorApplicationSecret:
    description: 'Password for the Orchestrator account'
    required: true
  orchestratorApplicationScope:
    description: 'Access scope for external application'
    required: false
    default: "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Users.Read"
  orchestratorLogicalName:
    description: 'Logical name for Orchestrator organization'
    required: true
outputs:
  testExecutionLinks:
    description: 'Outputs a comma-separated list of Orchestrator links for viewing test results'
    value: ${{ steps.run_tests.outputs.testExecutionLinks }}
  testResults:
    description: 'Markdown formatted table listing the tests that have been run and whether they passed or failed'
    value: ${{ steps.run_tests.outputs.testResults }}
  containsPublishableTestCases:
    description: 'Boolean value indicating whether any test cases set as publishable were found in the repository'
    value: ${{ steps.run_tests.outputs.containsPublishableTestCases }}

runs:
  using: "composite"
  steps:
    - id: get_folder_id
      name: Get Folder ID
      shell: bash
      run: |
        headers="Content-Type: application/x-www-form-urlencoded"
        orchestratorURL="${{ inputs.orchestratorUrl%/ }}"
        clientId=$(echo -n "${{ inputs.orchestratorApplicationId }}" | jq -sRr @uri)
        clientSecret=$(echo -n "${{ inputs.orchestratorApplicationSecret }}" | jq -sRr @uri)
        scope=$(echo -n "${{ inputs.orchestratorApplicationScope }}" | jq -sRr @uri)

        body="grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&scope=$scope"
        authResponse=$(curl -s -X POST "$orchestratorURL/identity_/connect/token" -H "$headers" -d "$body")
        accessToken=$(echo "$authResponse" | jq -r '.access_token')

        folderName="${{ inputs.orchestratorFolder }}"
        parameters="\$Filter=FullyQualifiedName eq '$folderName'"
        folderRequestURL="$orchestratorURL/${{ inputs.orchestratorLogicalName }}/${{ inputs.orchestratorTenant }}/orchestrator_/odata/folders?$parameters"
        folderId=$(curl -s -X GET "$folderRequestURL" -H "Authorization: Bearer $accessToken" | jq -r '.value[0].Id')

        echo "folderId=$folderId" >> $GITHUB_OUTPUT

    - id: run_tests
      name: Test
      shell: bash
      run: |
        testsFailed=0
        testResultsFolder="${{ github.workspace }}/test-results"
        mkdir -p "$testResultsFolder"
        testResults=""
        testExecutionBaseURL="${{ inputs.orchestratorUrl }}${{ inputs.orchestratorLogicalName }}/${{ inputs.orchestratorTenant }}/orchestrator_/test/executions/"
        testExecutionURLs=""
        repositoryContainsTests=0

        if [ -z "${{ inputs.projectFilePaths }}" ]; then
          echo "Scanning full repository directory for project.json files"
          projectJsonFiles=$(find "${{ github.workspace }}" -type f -name "project.json")
        else
          echo "Getting full path for files given as inputs"
          projectJsonFiles=$(echo "${{ inputs.projectFilePaths }}" | tr '\r\n' '\n')
        fi

        for projectFile in $projectJsonFiles; do
          projectInfo=$(cat "$projectFile" | jq '.')
          targetFramework=$(echo "$projectInfo" | jq -r '.targetFramework')
          fileInfoCollection=$(echo "$projectInfo" | jq -r '.designOptions.fileInfoCollection')

          if [ "$(echo "$fileInfoCollection" | jq length)" -gt 0 ]; then
            publishableTests=$(echo "$fileInfoCollection" | jq '[.[] | select(.editingStatus == "Publishable")] | length')
            if [ "$publishableTests" -gt 0 ]; then
              repositoryContainsTests=1
              testResultFilePath="$testResultsFolder/$(echo "$projectInfo" | jq -r '.name')-testresults.json"

              echo "Running tests for project $(echo "$projectInfo" | jq -r '.name')"
              uipcli test run "${{ inputs.orchestratorUrl }}" "${{ inputs.orchestratorTenant }}" \
                --project-path "$projectFile" \
                --accountForApp "${{ inputs.orchestratorLogicalName }}" \
                --applicationId "${{ inputs.orchestratorApplicationId }}" \
                --applicationSecret "${{ inputs.orchestratorApplicationSecret }}" \
                --applicationScope "${{ inputs.orchestratorApplicationScope }}" \
                --organizationUnit "${{ inputs.orchestratorFolder }}" \
                --out uipath \
                --result_path "$testResultFilePath" \
                --language en-US

              testResultData=$(cat "$testResultFilePath" | jq '.')
              testCaseExecutions=$(echo "$testResultData" | jq '.TestSetExecutions.TestCaseExecutions')
              folderId="${{ steps.get_folder_id.outputs.folderId }}"
              testSetExecutionLink="$testExecutionBaseURL$(echo "$testResultData" | jq -r '.TestSetExecutions[0].Id')?fid=$folderId"

              echo "Test execution can be viewed in Orchestrator by clicking this link: $testSetExecutionLink"

              testResultsTable="| Test case | Result |\n| :-- | :-- |"
              while IFS= read -r testCase; do
                testName=$(echo "$testCase" | jq -r '.Name')
                testStatus=$(echo "$testCase" | jq -r '.Status')
                testResultsTable+="\n| $testName | $(if [ "$testStatus" == "Passed" ]; then echo ":white_check_mark: Passed"; else echo ":x: Failed"; fi) |"
              done < <(echo "$testCaseExecutions" | jq -c '.[]')

              testResults+="\n### [Test results for $(echo "$testResultData" | jq -r '.TestSetExecutions[0].Name')]($testSetExecutionLink)\n$testResultsTable"

              if [ -z "$testExecutionURLs" ]; then
                testExecutionURLs="$testSetExecutionLink"
              else
                testExecutionURLs+=", $testSetExecutionLink"
              fi

              if [ $? -ne 0 ]; then
                testsFailed=1
              fi
            else
              echo "$(echo "$projectInfo" | jq -r '.name') contains no test cases set as publishable. Testing skipped."
              testResults+="\n- :warning: **$(echo "$projectInfo" | jq -r '.name') contains no test cases set as publishable. Testing skipped.**\n"
            fi
          else
            echo "$(echo "$projectInfo" | jq -r '.name') contains no test cases. Testing skipped."
            testResults+="\n- :warning: **$(echo "$projectInfo" | jq -r '.name') contains no test cases. Testing skipped.**\n"
          fi
        done

        echo "testExecutionLinks=$testExecutionURLs" >> $GITHUB_OUTPUT
        echo -e "testResults<<EOF\n$testResults\nEOF" >> $GITHUB_OUTPUT

        if [ "$repositoryContainsTests" -eq 0 ]; then
          echo "No publishable UiPath test cases were found in this repository. Testing has been skipped." > "$testResultsFolder/test.txt"
          echo "containsPublishableTestCases=false" >> $GITHUB_OUTPUT
        else
          echo "containsPublishableTestCases=true" >> $GITHUB_OUTPUT
        fi

        echo -e "$testResults" >> $GITHUB_STEP_SUMMARY

        if [ "$testsFailed" -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi

    - id: print_outputs
      name: Print outputs
      if: always()
      shell: bash
      run: |
        echo "${{ steps.run_tests.outputs.testExecutionLinks }}"
        echo "${{ steps.run_tests.outputs.testResults }}"
