name: 'UiPath Test'
description: 'Runs test cases within a UiPath project'
inputs:
  orchestratorUrl: 
    description: 'Orchestrator instance URL'
    required: true
  orchestratorTenant:
    description: 'Tenant on the Orchestrator instance'
    required: true
  orchestratorFolder:
    description: 'Folder path in modern folder setup'
    required: true
  orchestratorApplicationId:
    description: 'Account for authenticating to Orchestrator'
    required: true
  orchestratorApplicationSecret:
    description: 'Password for the Orchestrator account'
    required: true
  orchestratorApplicationScope:
    description: 'Access scope for external application'
    required: true
  orchestratorLogicalName:
    description: 'Logical name for Orchestrator organization'
    required: true

runs:
  using: "composite"
  steps:
    - name: Test
      shell: pwsh
      run: |
        $testsFailed = 0
        $projectList = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter *.nupkg -File
        foreach($project in $projectList)
        {
          Write-Host "$($project.FullName)"
          & uipcli test run ${{ inputs.orchestratorUrl }} ${{ inputs.orchestratorTenant }} -P "$($project.FullName)" --accountForApp "${{ inputs.orchestratorLogicalName }}" --applicationId  "${{ inputs.orchestratorApplicationId }}" --applicationSecret "${{ inputs.orchestratorApplicationSecret }}" --applicationScope "${{ inputs.orchestratorApplicationScope }}" --organizationUnit "${{ inputs.orchestratorFolder }}" --language en-US
          if($LASTEXITCODE -ne 0)
          {
            $testsFailed = 1
          }
        }
        if($testsFailed -ne 0)
        {
          throw "Tests failed"
        }
